883468  - How to make Winforms PdfViewer to have enriched features like WPF PdfViewer.
syncfusion-content/windowsforms-docs pull request #1089
Opened 2024-11-11 13:09 UTC by Dhileep4290

**Description:**
                  Created UG for the How to section by adding separate UG content for the Hosting of WPF Pdfviewer in Winforms
                   *  This code change is for the UG for the Hosting of WPF PdfViewer in Winforms in the How to section of Winforms UG
                   *  Added detailed descriptions, examples, and guidelines for the UG for the Hosting of WPF PdfViewer in Winforms with code example.
                   * Added a seaparate md file for the UG for the Hosting of WPF PdfViewer in Winforms that is added as separate section in the How to section in Winforms UG

2024-11-11 13:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [883468-Integrating-WPF_to_Winforms_UG](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/237/console)**

2024-11-11 13:16 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/237/artifact/cireports/)<br/>Build Location: [883468-Integrating-WPF_to_Winforms_UG](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/237/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/237/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/237/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/237/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/237/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [4](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/237/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/237/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/237/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/237/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [1](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/237/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-11 13:42 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [883468-Integrating-WPF_to_Winforms_UG](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/239/console)**

2024-11-11 13:47 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [883468-Integrating-WPF_to_Winforms_UG](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/239/console)**

2024-11-12 06:09 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [883468-Integrating-WPF_to_Winforms_UG](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/244/console)**

2024-11-12 06:17 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [883468-Integrating-WPF_to_Winforms_UG](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/244/console)**

2024-11-12 06:20 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/244/artifact/cireports/)<br/>Build Location: [883468-Integrating-WPF_to_Winforms_UG](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/244/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/244/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/244/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/244/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/244/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/244/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/244/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/244/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/244/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [1](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/244/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-12 07:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [883468-Integrating-WPF_to_Winforms_UG](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/245/console)**

2024-11-12 07:01 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [883468-Integrating-WPF_to_Winforms_UG](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/245/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/245/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/245/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/245/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/245/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/245/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/245/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/245/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/245/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/245/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-15 12:55 UTC, RajaVigneshB requested changes

2024-11-15 12:55 UTC, RajaVigneshB commented on WindowsForms/PDF-Viewer/How-To/How-to-make-Winforms-PdfViewer-have-enriched-features-like-WPF-PdfViewer.md
> +Currently the Syncfusion Windows Forms PdfViewer lacks support for the features, such as adding annotations, form filling, signatures, stamps, sticky notes, etc., which are available in the WPF PdfVi
Add the KB link this in the discussed content

2024-11-15 12:55 UTC, RajaVigneshB commented on WindowsForms/PDF-Viewer/How-To/How-to-make-Winforms-PdfViewer-have-enriched-features-like-WPF-PdfViewer.md
> +
As we discussed, please modify the complete document

2024-11-15 14:24 UTC, Dhileep4290 commented on WindowsForms/PDF-Viewer/How-To/How-to-make-Winforms-PdfViewer-have-enriched-features-like-WPF-PdfViewer.md
> +Currently the Syncfusion Windows Forms PdfViewer lacks support for the features, such as adding annotations, form filling, signatures, stamps, sticky notes, etc., which are available in the WPF PdfVi
Added the KB link

2024-11-15 14:24 UTC, Dhileep4290 commented on WindowsForms/PDF-Viewer/How-To/How-to-make-Winforms-PdfViewer-have-enriched-features-like-WPF-PdfViewer.md
> +
Modified the content and added explanation for the code

2024-11-15 14:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [883468-Integrating-WPF_to_Winforms_UG](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/247/console)**

2024-11-15 14:30 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [883468-Integrating-WPF_to_Winforms_UG](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/247/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/247/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/247/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/247/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/247/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/247/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/247/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/247/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/247/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/247/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-18 09:28 UTC, RajaVigneshB requested changes

2024-11-18 09:28 UTC, RajaVigneshB commented on WindowsForms/PDF-Viewer/How-To/How-to-make-Winforms-PdfViewer-have-enriched-features-like-WPF-PdfViewer.md
> +1. **Adding the ElementHost Control:**
The format of the UG was not followed here. Why we are using Asterix for the heading here?

2024-11-19 12:01 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [883468-Integrating-WPF_to_Winforms_UG](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/248/console)**

2024-11-19 12:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [883468-Integrating-WPF_to_Winforms_UG](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/248/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/248/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/248/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/248/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/248/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/248/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/248/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/248/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/248/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/248/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-27 11:24 UTC, Vikassekar requested changes
As we discuss do the changes

2024-11-27 12:07 UTC, RajaVigneshB approved these changes

2024-11-27 12:16 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [883468-Integrating-WPF_to_Winforms_UG](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/271/console)**

2024-11-28 08:38 UTC, Vikassekar requested changes

2024-11-28 08:38 UTC, Vikassekar commented on WindowsForms/PDF-Viewer/How-To/How-to-make-Winforms-PdfViewer-have-enriched-features-like-WPF-PdfViewer.md
> +    public partial class PdfViewer : UserControl
as discussed in the feedback call change the class name as PdfViewerUserControl

2024-11-28 08:38 UTC, Vikassekar commented on WindowsForms/PDF-Viewer/How-To/How-to-make-Winforms-PdfViewer-have-enriched-features-like-WPF-PdfViewer.md
> +            PdfViewer pdfViewer = new PdfViewer();
as discussed in the feedback call, change  PdfViewerUserControl for custom control

2024-11-28 08:54 UTC, Dhileep4290 commented on WindowsForms/PDF-Viewer/How-To/How-to-make-Winforms-PdfViewer-have-enriched-features-like-WPF-PdfViewer.md
> +    public partial class PdfViewer : UserControl
changed the class name

2024-11-28 08:54 UTC, Dhileep4290 commented on WindowsForms/PDF-Viewer/How-To/How-to-make-Winforms-PdfViewer-have-enriched-features-like-WPF-PdfViewer.md
> +            PdfViewer pdfViewer = new PdfViewer();
changed the custom control's name

2024-11-28 10:28 UTC, Vikassekar approved these changes
Approving this

2024-11-28 10:30 UTC, Vikassekar requested changes

2024-11-28 10:30 UTC, Vikassekar commented on WindowsForms/PDF-Viewer/How-To/How-to-make-Winforms-PdfViewer-have-enriched-features-like-WPF-PdfViewer.md
> +{% endtabs %}
Can you add the sample link for this UG like in the KB below https://support.syncfusion.com/kb/article/7882/how-to-host-pdf-viewer-in-windows-forms-application

2024-11-28 10:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [883468-Integrating-WPF_to_Winforms_UG](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/275/console)**

2024-11-28 10:53 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [883468-Integrating-WPF_to_Winforms_UG](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/275/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/275/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/275/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/275/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/275/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/275/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/275/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/275/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/275/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/275/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-28 11:01 UTC, Vikassekar approved these changes

2024-11-28 11:01 UTC, merged