SEO-2050_Site_Audit_Issues
syncfusion-content/windowsforms-docs pull request #149
Opened 2022-03-24 11:25 UTC by gowthamanthavasiyappan

Hi @ChristoIssac,

Worked on Bing report issues, merge these changes.

Regards,
Gowthaman

2022-03-24 11:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-2050_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/232/console)**

2022-03-24 11:29 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-2050_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/232/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/232/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/232/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/232/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/232/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/232/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/232/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-03-25 06:02 UTC, ChristoIssac requested changes

2022-03-25 06:02 UTC, ChristoIssac commented on WindowsForms/Docking-Manager/FAQ/General/How-to-Enable-the-Tabbed-Style-Dockable-Window-using-TabbedMDI-manager.md
> +description: How to Enable the Tabbed Style Dockable Window using Syncfusion WinForms DockingManager Control, its elements, and more.
Seems it's Tabbed MDI Manager

2022-03-29 11:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-2050_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/240/console)**

2022-03-29 11:16 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-2050_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/240/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/240/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/240/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/240/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/240/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/240/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/240/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-03-29 11:29 UTC, gowthamanthavasiyappan commented on WindowsForms/Docking-Manager/FAQ/General/How-to-Enable-the-Tabbed-Style-Dockable-Window-using-TabbedMDI-manager.md
> +description: How to Enable the Tabbed Style Dockable Window using Syncfusion WinForms DockingManager Control, its elements, and more.
Changed

2022-03-29 11:30 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-2050_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/241/console)**

2022-03-29 11:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-2050_Site_Audit_Issues](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/241/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/241/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/241/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/241/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/241/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/241/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/241/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-03-31 11:59 UTC, ChristoIssac approved these changes

2022-03-31 11:59 UTC, merged