WF-63043 Need to update the Maps UG Content.
syncfusion-content/windowsforms-docs pull request #188
Opened 2022-05-06 02:38 UTC by EswaranSyncfusion

Hi @vigneshrameshsync ,

Maps UG Content is modified, So please review the content changes and let me know if you have any other concerns.

Regards,
@EswaranSyncfusion

2022-05-06 02:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF63043_hotfix](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/261/console)**

2022-05-06 02:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF63043_hotfix](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/261/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/261/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/261/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/261/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/261/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/261/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/261/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-05-09 07:55 UTC, vigneshrameshsync requested changes

2022-05-09 07:55 UTC, vigneshrameshsync commented on WindowsForms/Map/Customizing-Map-appearance.md
> +![Equal Color Mapping in Windows Forms Map](Customizing-Map-appearance_images/Customizing-Map-appearance_img2.png)
Provide proper name for image like "customizing-map-appearance-with-equal-color-mapping"

2022-05-09 07:55 UTC, vigneshrameshsync commented on WindowsForms/Map/Customizing-Map-appearance.md
> +![Equal Color Mapping in Windows Forms Map](Customizing-Map-appearance_images/Customizing-Map-appearance_img2.png)
If the LabelIntersection option is there, then set it as trim or hide. It is very odd to see the intersection labels in output image.

2022-05-10 03:43 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF63043_hotfix](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/263/console)**

2022-05-10 03:45 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF63043_hotfix](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/263/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/263/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/263/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/263/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/263/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/263/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/263/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-05-11 03:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF63043_hotfix](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/265/console)**

2022-05-11 03:52 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF63043_hotfix](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/265/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/265/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/265/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/265/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/265/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/265/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/265/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-05-11 04:02 UTC, EswaranSyncfusion commented on WindowsForms/Map/Customizing-Map-appearance.md
> +![Equal Color Mapping in Windows Forms Map](Customizing-Map-appearance_images/Customizing-Map-appearance_img2.png)
Proper image name is provided

2022-05-11 04:03 UTC, EswaranSyncfusion commented on WindowsForms/Map/Customizing-Map-appearance.md
> +![Equal Color Mapping in Windows Forms Map](Customizing-Map-appearance_images/Customizing-Map-appearance_img2.png)
LabelIntersection option is not there so i hide the value text.

2022-05-11 04:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF63043_hotfix](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/266/console)**

2022-05-11 04:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF63043_hotfix](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/266/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/266/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/266/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/266/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/266/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/266/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/266/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-05-11 06:08 UTC, vigneshrameshsync approved these changes
The changes are fine.

2022-05-11 06:59 UTC, sheiksyedm approved these changes

2022-05-11 06:59 UTC, merged