WF-63508 Prepared UG content for SmithChart
syncfusion-content/windowsforms-docs pull request #236
Opened 2022-06-15 19:35 UTC by TamilarasanGunasekaran

Hi @vigneshrameshsync ,
                 I have prepared UG content for SmithChart.

2022-06-15 19:36 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/293/console)**

2022-06-15 19:37 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/293/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/293/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/293/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/293/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/293/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/293/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/293/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-16 06:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/294/console)**

2022-06-16 06:52 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: Not Started :x:<br/>Failure Reason: [Source Checkout](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/294/)<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/294/)<br/>**

2022-06-16 06:56 UTC, TamilarasanGunasekaran commented
rebuild

2022-06-16 06:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/295/console)**

2022-06-16 06:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/295/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/295/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/295/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/295/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/295/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/295/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/295/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-16 18:35 UTC, vigneshrameshsync requested changes

2022-06-16 18:35 UTC, vigneshrameshsync commented on WindowsForms/Smith-Chart/Series.md
> +## Customizing Series Data
Please do the same changes here as I have mentioned in below PR
https://github.com/syncfusion-content/wpf-docs/pull/295

2022-06-17 13:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/299/console)**

2022-06-17 13:20 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/299/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/299/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/299/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/299/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/299/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/299/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/299/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-17 13:33 UTC, vigneshrameshsync commented on WindowsForms/Smith-Chart/Series.md
> +series.ArrangeByIndex = true
Did you build this code in VB?

2022-06-17 16:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/300/console)**

2022-06-18 06:38 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/301/console)**

2022-06-18 06:39 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/301/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/301/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/301/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/301/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/301/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/301/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/301/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-18 06:39 UTC, vigneshrameshsync approved these changes
The content is fine.

2022-06-20 05:29 UTC, OnyimbiNelson commented on WindowsForms/Smith-Chart/Series.md
> +The property *ArrangeByIndex* value is indicating whether to render the data based on the provided index order. the data points are rendered based on the provided index when it is true otherwise, the
The property *ArrangeByIndex* value indicates whether to render the data based on the provided index order. The data points are rendered based on the provided index when it is 'true', otherwise, the data points are rendered by sorting based on their resistance value.

2022-06-20 05:30 UTC, OnyimbiNelson commented on WindowsForms/Smith-Chart/Series.md
> +The default value is false.
The default value is 'false'.

2022-06-20 06:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/302/console)**

2022-06-20 07:21 UTC, TamilarasanGunasekaran commented
rebuild

2022-06-20 07:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/303/console)**

2022-06-20 07:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/303/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/303/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/303/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/303/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/303/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/303/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/303/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-20 08:24 UTC, merged