SEO-3239 Windowsforms Page with redirect
syncfusion-content/windowsforms-docs pull request #419
Opened 2023-02-14 10:13 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan ,

Please review the changes for Windowsforms Page with redirect.

Regards,
Yvone.

2023-02-14 10:14 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3239-Windowsforms-Page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/421/console)**

2023-02-14 10:15 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3239-Windowsforms-Page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/421/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/421/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/421/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/421/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/421/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/421/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/421/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-15 04:16 UTC, gowthamanthavasiyappan requested changes

2023-02-15 04:16 UTC, gowthamanthavasiyappan commented on WindowsForms/layoutmanagers/FlowLayout.md
> +[Creating a simple Layout](/windowsforms/layoutmanagers/creating-a-simple-layout), [Child Control Settings](https://help.syncfusion.com/windowsforms/layoutmanagers/layout-manager-settings#child-contr
Revert this `https://help.syncfusion.com`

2023-02-16 06:14 UTC, gowthamanthavasiyappan commented
Commented

2023-02-16 06:29 UTC, Yvone-Atieno commented on WindowsForms/layoutmanagers/FlowLayout.md
> +[Creating a simple Layout](/windowsforms/layoutmanagers/creating-a-simple-layout), [Child Control Settings](https://help.syncfusion.com/windowsforms/layoutmanagers/layout-manager-settings#child-contr
reverted

2023-02-16 06:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3239-Windowsforms-Page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/424/console)**

2023-02-16 06:34 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3239-Windowsforms-Page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/424/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/424/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/424/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/424/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/424/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/424/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/424/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-16 07:17 UTC, gowthamanthavasiyappan approved these changes

2023-02-21 07:06 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-02-21 07:06 UTC, merged