SEO-171714 - Window Forms Page with redirect
syncfusion-content/windowsforms-docs pull request #529
Opened 2023-05-08 09:12 UTC by SellineRita

HI @Aishwarya-Ganesan ,
Please review changes for Window Forms redirect links.

Regards,
Selline Rita.

2023-05-08 09:13 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-171714-WindowForms-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/501/console)**

2023-05-08 09:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171714-WindowForms-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/501/console)**

2023-05-08 09:18 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171714-WindowForms-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/501/)<br/>**

2023-05-10 03:33 UTC, gowthamanthavasiyappan requested changes
Commented

2023-05-10 03:33 UTC, gowthamanthavasiyappan commented on WindowsForms/Grid-Control/Cell-Style-Architecture.md
> +For clearing only the selected range of cells, make use of the [Model.Clear](https://help.syncfusion.com/cr/windowsforms/Syncfusion.Windows.Forms.Grid.GridStyleInfo.html#Syncfusion_Windows_Forms_Grid
Recheck this link.

2023-05-16 12:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171714-WindowForms-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/506/console)**

2023-05-16 12:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171714-WindowForms-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/506/)<br/>**

2023-05-18 03:36 UTC, Girija-Rajendran commented on WindowsForms/DataGrid/InteractiveFeatures.MD
> +The context menu for the group summary can be set by using [SfDataGrid.GroupSummaryContextMenu](https://help.syncfusion.com/cr/windowsforms/Syncfusion.WinForms.DataGrid.SfDataGrid.html#Syncfusion_Win
Is this correct?

2023-05-18 03:38 UTC, Girija-Rajendran commented on WindowsForms/DataGrid/InteractiveFeatures.MD
> +N>[GridColumnBase.ShowToolTip](https://help.syncfusion.com/cr/windowsforms/Syncfusion.WinForms.DataGrid.SfDataGrid.html#Syncfusion_WinForms_DataGrid_SfDataGrid_ShowToolTip) takes higher priority than
Recheck this link

2023-05-18 03:39 UTC, Girija-Rajendran commented on WindowsForms/Grid-Control/Cell-Style-Architecture.md
> +Custom BaseStyles can be defined in GridControl by using the [GridBaseStyle](hhttps://help.syncfusion.com/cr/windowsforms/Syncfusion.Windows.Forms.Grid.GridBaseStyle.html). After defining a BaseStyle
<img width="982" alt="image" src="https://github.com/syncfusion-content/windowsforms-docs/assets/61148953/1c19ecc5-51e0-4cb6-a336-c4918e06ff01">

2023-05-18 06:52 UTC, SellineRita commented on WindowsForms/DataGrid/InteractiveFeatures.MD
> +N>[GridColumnBase.ShowToolTip](https://help.syncfusion.com/cr/windowsforms/Syncfusion.WinForms.DataGrid.SfDataGrid.html#Syncfusion_WinForms_DataGrid_SfDataGrid_ShowToolTip) takes higher priority than
Reverted changes

2023-05-18 06:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171714-WindowForms-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/507/console)**

2023-05-18 06:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171714-WindowForms-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/507/)<br/>**

2023-05-18 07:19 UTC, SellineRita commented on WindowsForms/DataGrid/InteractiveFeatures.MD
> +The context menu for the group summary can be set by using [SfDataGrid.GroupSummaryContextMenu](https://help.syncfusion.com/cr/windowsforms/Syncfusion.WinForms.DataGrid.SfDataGrid.html#Syncfusion_Win
Updated correct link.

2023-05-18 11:34 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-171714-WindowForms-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/508/console)**

2023-05-18 11:35 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/508/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-05-18 11:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171714-WindowForms-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/508/console)**

2023-05-18 11:35 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-171714-WindowForms-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/509/console)**

2023-05-18 11:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171714-WindowForms-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/509/console)**

2023-05-18 11:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171714-WindowForms-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/508/)<br/>**

2023-05-18 11:39 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171714-WindowForms-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/509/)<br/>**

2023-05-19 06:52 UTC, Girija-Rajendran commented on WindowsForms/Grid-Control/Cell-Style-Architecture.md
> +[ImageList](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.imagelist?view=windowsdesktop-7.0&viewFallbackFrom=net-5.0) property holds [Systems.Windows.Forms.ImageList](https://lear
is this correct?

2023-05-19 07:40 UTC, SellineRita commented on WindowsForms/Grid-Control/Cell-Style-Architecture.md
> +[ImageList](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.imagelist?view=windowsdesktop-7.0&viewFallbackFrom=net-5.0) property holds [Systems.Windows.Forms.ImageList](https://lear
Updated correct link.

2023-05-22 08:44 UTC, Girija-Rajendran approved these changes

2023-05-22 08:44 UTC, merged