SEO-172160-Wndowsforms-redirect
syncfusion-content/windowsforms-docs pull request #540
Opened 2023-05-24 08:18 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan ,

Have changed redirect links in Windowsforms, please review.

Regards,
Yvone.

2023-05-24 08:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172160-Windowsform-redirect](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/514/console)**

2023-05-24 10:38 UTC, MallikaRK requested changes
commented

2023-05-24 10:38 UTC, MallikaRK commented on WindowsForms/DataGrid/ExportToPDF.md
> +f---
revert it.

2023-05-24 11:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172160-Windowsform-redirect](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/518/console)**

2023-05-24 11:53 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172160-Windowsform-redirect](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/518/)<br/>**

2023-05-24 12:16 UTC, Yvone-Atieno commented on WindowsForms/DataGrid/ExportToPDF.md
> +f---
reverted

2023-05-24 12:38 UTC, MallikaRK approved these changes
Approved

2023-05-26 04:26 UTC, Girija-Rajendran approved these changes

2023-05-26 04:27 UTC, merged