SEO-172143 page with redirect links
syncfusion-content/windowsforms-docs pull request #544
Opened 2023-05-24 12:41 UTC by Scholar-jaruha

Hi @MallikaRK,
Please review changes made
Regards,
Scholar.

2023-05-24 12:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172143-Windowsforms-Controls](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/519/console)**

2023-05-24 12:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172143-Windowsforms-Controls](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/519/)<br/>**

2023-05-25 10:13 UTC, MallikaRK requested changes
Commented

2023-05-25 10:13 UTC, MallikaRK commented on WindowsForms/Gradient-Label/Getting-Started.md
> +![Windows Forms GradientLabel shows grdient style](gradientlabel-images/windowsforms-gradientlabel_style.jpeg)
give hypen in between gradientlabel.
gradient-label-style
[Use the image name in same format, hypen[-], undescrore[_] both are used here. Use hypen symbol for image name]
Remove _ [underscore] and use Hypen for all places.

2023-05-25 10:13 UTC, MallikaRK commented on WindowsForms/Gradient-Panel/Getting-Started.md
> +![Windows Forms GradientPanel drag and drop from toolbox](gradientpanel-images/windowsforms-gradientpanel_toolbox.png)
recheck

2023-05-26 04:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172143-Windowsforms-Controls](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/529/console)**

2023-05-26 04:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172143-Windowsforms-Controls](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/529/)<br/>**

2023-05-26 07:28 UTC, Scholar-jaruha commented on WindowsForms/Gradient-Label/Getting-Started.md
> +![Windows Forms GradientLabel shows grdient style](gradientlabel-images/windowsforms-gradientlabel_style.jpeg)
changed

2023-05-26 07:28 UTC, Scholar-jaruha commented on WindowsForms/Gradient-Panel/Getting-Started.md
> +![Windows Forms GradientPanel drag and drop from toolbox](gradientpanel-images/windowsforms-gradientpanel_toolbox.png)
changed

2023-06-01 07:48 UTC, MallikaRK requested changes

2023-06-02 08:29 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-172143-Windowsforms-Controls](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/582/console)**

2023-06-02 08:33 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/582/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-06-02 08:34 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-172143-Windowsforms-Controls](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/583/console)**

2023-06-02 08:34 UTC, Scholar-jaruha commented on WindowsForms/Gradient-Label/Getting-Started.md
> +![Drag and drop GradientLabel from toolbox](gradient-label-images/windowsforms-gradient-label-toolbox.jpeg)
Changed

2023-06-09 11:22 UTC, MallikaRK requested changes
Commented

2023-06-09 11:22 UTC, MallikaRK commented on WindowsForms/gradientpanelext/Getting-Started.md
> +4. Add the primitives to the control using **GradientPanelExt PrimitiveCollection Editor**, which is displayed using the [Primitives](https://help.syncfusion.com/cr/windowsforms/Syncfusion.Windows.Fo
Update the valid URL here. This URL seems wrong.

2023-06-12 09:17 UTC, MallikaRK requested changes
Commented

2023-06-12 09:17 UTC, MallikaRK commented on WindowsForms/Gradient-Label/Getting-Started.md
> +![Windows Forms GradientLabel shows grdient style](gradient-label-images/windowsforms-gradient-label_style.jpeg)
Already said, don't use underscore in image name. 
windowsforms-gradient-label**_**style.jpeg - wrong

windowsforms-gradient-label**-**style.jpeg
Use hyphen for image names.
Check and update it.

2023-06-12 09:17 UTC, MallikaRK commented on WindowsForms/gradientpanelext/Getting-Started.md
> +4. Add the primitives to the control using **GradientPanelExt PrimitiveCollection Editor**, which is displayed using the [Primitives](https://help.syncfusion.com/cr/windowsforms/Syncfusion.Windows.Fo
This is the valid link
https://help.syncfusion.com/cr/windowsforms/Syncfusion.Windows.Forms.Tools.GradientPanelExt.html#Syncfusion_Windows_Forms_Tools_GradientPanelExt_Primitives

please check and update valid links in further your works.

2023-06-12 09:17 UTC, MallikaRK commented on WindowsForms/gradientpanelext/Getting-Started.md
> +![WindowsForms Gradient Panel showing primitive collection editor](gradient-panel_images/windowsforms-gradient-panel-collection-editor.png)
Which one is correct image folder name?
<img width="830" alt="image" src="https://github.com/syncfusion-content/windowsforms-docs/assets/44014283/a6bf76ae-504c-4220-b601-6ed9374c3e6c">
Use the proper image folder name.

2023-06-12 09:17 UTC, MallikaRK commented on WindowsForms/gradientpanelext/Getting-Started.md
> +![WindowsForms Gradient Panel shows added primitives and other controls](gradient-panel_images\windowsforms-gradient-panel-addcontrols.png)
Check and change the Image Folder name in all places.

2023-06-14 05:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172143-Windowsforms-Controls](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/593/console)**

2023-06-14 05:49 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172143-Windowsforms-Controls](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/593/)<br/>**

2023-06-14 07:33 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-172143-Windowsforms-Controls](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/594/console)**

2023-06-14 07:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172143-Windowsforms-Controls](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/594/console)**

2023-06-14 07:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172143-Windowsforms-Controls](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/594/)<br/>**

2023-06-19 07:12 UTC, Scholar-jaruha commented on WindowsForms/gradientpanelext/Getting-Started.md
> +![WindowsForms Gradient Panel showing primitive collection editor](gradient-panel_images/windowsforms-gradient-panel-collection-editor.png)
Issue Fixed

2023-06-19 07:12 UTC, Scholar-jaruha commented on WindowsForms/gradientpanelext/Getting-Started.md
> +![WindowsForms Gradient Panel shows added primitives and other controls](gradient-panel_images\windowsforms-gradient-panel-addcontrols.png)
Issue resolved

2023-06-19 07:12 UTC, Scholar-jaruha commented on WindowsForms/Gradient-Label/Getting-Started.md
> +![Windows Forms GradientLabel shows grdient style](gradient-label-images/windowsforms-gradient-label_style.jpeg)
Issue resolved

2023-06-19 07:12 UTC, Scholar-jaruha commented on WindowsForms/gradientpanelext/Getting-Started.md
> +4. Add the primitives to the control using **GradientPanelExt PrimitiveCollection Editor**, which is displayed using the [Primitives](https://help.syncfusion.com/cr/windowsforms/Syncfusion.Windows.Fo
Issue resolved

2023-06-21 05:37 UTC, MallikaRK approved these changes
Approved

2023-06-22 10:24 UTC, Girija-Rajendran approved these changes

2023-06-22 10:32 UTC, merged