SEO-172160-WindowsForms-Weblink-Issue
syncfusion-content/windowsforms-docs pull request #557
Opened 2023-05-26 09:55 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan ,

Have changed image alt and renamed images in md and folder.

Regards,
Yvone.

2023-05-26 09:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172160-WindowsForms-Weblink-Issues](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/536/console)**

2023-05-26 09:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172160-WindowsForms-Weblink-Issues](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/536/)<br/>**

2023-06-12 09:09 UTC, MallikaRK requested changes
Commented

2023-06-12 09:09 UTC, MallikaRK commented on WindowsForms/chart/FAQ/How-to-add-an-image-on-chart-area.md
> +![Adding an image on chart area in WindowsForms application](how-to-add-image-on-chart-area/windowsforms-chart-adding-image-on-chart-area.png)
Don't use repeated keywords in image name. you used chart keyword in 2 places.
adding-image-on-winforms-chart-area - is fine.
update it.

2023-06-12 09:09 UTC, MallikaRK commented on WindowsForms/chart/FAQ/How-to-display-custom-tooltip-over-Histogram-Chart.md
> +![Chart Histogram in WindowsForms application](how-to-display-custom-tooltip-over-histogram-chart_images/windowsforms-charthistogram-chart.jpeg)
Image name seems wrong. check and update.
windowsforms-histogram-chart

2023-06-12 09:12 UTC, Yvone-Atieno commented on WindowsForms/chart/FAQ/How-to-add-an-image-on-chart-area.md
> +![Adding an image on chart area in WindowsForms application](how-to-add-image-on-chart-area/windowsforms-chart-adding-image-on-chart-area.png)
changed

2023-06-12 09:31 UTC, Yvone-Atieno commented on WindowsForms/chart/FAQ/How-to-display-custom-tooltip-over-Histogram-Chart.md
> +![Chart Histogram in WindowsForms application](how-to-display-custom-tooltip-over-histogram-chart_images/windowsforms-charthistogram-chart.jpeg)
changed

2023-06-12 09:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172160-WindowsForms-Weblink-Issues](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/591/console)**

2023-06-12 09:32 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172160-WindowsForms-Weblink-Issues](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/591/)<br/>**

2023-06-12 09:41 UTC, MallikaRK requested changes
Commented

2023-06-12 09:44 UTC, Yvone-Atieno commented on WindowsForms/chart/FAQ/How-to-add-an-image-on-chart-area.md
> +![Adding an image on chart area in WindowsForms application](how-to-add-image-on-chart-area/windowsforms-adding-image-on-chart-area.png)
changed

2023-06-12 09:49 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172160-WindowsForms-Weblink-Issues](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/592/console)**

2023-06-12 09:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172160-WindowsForms-Weblink-Issues](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/592/)<br/>**

2023-06-12 11:15 UTC, MallikaRK approved these changes
Approved

2023-06-12 11:52 UTC, Girija-Rajendran approved these changes

2023-06-12 11:52 UTC, merged