SEO-172143 Windowsforms links
syncfusion-content/windowsforms-docs pull request #567
Opened 2023-05-29 08:50 UTC by Scholar-jaruha

Hi @MallikaRK ,
Please find the changes made.
Regards,
Scholar.

2023-05-29 08:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172143-Windowsforms-links](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/551/console)**

2023-05-29 08:52 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172143-Windowsforms-links](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/551/)<br/>**

2023-05-30 08:32 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172143-Windowsforms-links](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/560/)<br/>**

2023-06-12 09:27 UTC, MallikaRK requested changes
Commented

2023-06-12 09:27 UTC, MallikaRK commented on WindowsForms/GridGrouping/Data-Binding.md
> +![Unbound Column in WindowsForms](data-binding_images/windowsforms-grid-grouping-unbound-column.jpeg)
Control name missing in ALT Text.

2023-06-12 09:27 UTC, MallikaRK commented on WindowsForms/GridGrouping/Data-Binding.md
> +![Implementation in WindowsForms](data-binding_images/windowsforms-gridgrouping-implementation.jpeg)
Control name is missing in ALT Text for all places. Check and add the proper control name in all places.

2023-06-12 09:27 UTC, MallikaRK commented on WindowsForms/GridGrouping/Getting-Started.md
> +![Windowsforms gridgroupingcontrol is dragged from toolbox](getting-started_images/windowsforms-grid-grouping-dragged-toolbox.png)
In Alt text, windows forms also the valid keyword. Don't change hereafter.

2023-06-12 09:27 UTC, MallikaRK commented on WindowsForms/GridRecordNavigationControl/Getting-Started.md
> +   ![Drag and Drop Toolbox in WindowsForms](creating-grid-record-navigation-control_images/windowsforms-drag-drop-toolbox.jpeg)
Control name missing in image name.
<img width="714" alt="image" src="https://github.com/syncfusion-content/windowsforms-docs/assets/44014283/49e4a5e8-5e2e-432f-b0c4-d4c2507b90a6">
Check and correct the changes in all places.

2023-06-14 08:40 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172143-Windowsforms-links](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/596/console)**

2023-06-23 08:34 UTC, Scholar-jaruha commented on WindowsForms/GridGrouping/Data-Binding.md
> +![Implementation in WindowsForms](data-binding_images/windowsforms-gridgrouping-implementation.jpeg)
added

2023-06-23 08:34 UTC, Scholar-jaruha commented on WindowsForms/GridGrouping/Data-Binding.md
> +![Unbound Column in WindowsForms](data-binding_images/windowsforms-grid-grouping-unbound-column.jpeg)
added

2023-06-23 08:39 UTC, Scholar-jaruha commented on WindowsForms/GridGrouping/Getting-Started.md
> +![Windowsforms gridgroupingcontrol is dragged from toolbox](getting-started_images/windowsforms-grid-grouping-dragged-toolbox.png)
okay, sure

2023-06-23 08:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172143-Windowsforms-links](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/607/console)**

2023-06-23 08:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172143-Windowsforms-links](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/607/)<br/>**

2023-06-23 08:44 UTC, Scholar-jaruha commented on WindowsForms/GridRecordNavigationControl/Getting-Started.md
> +   ![Drag and Drop Toolbox in WindowsForms](creating-grid-record-navigation-control_images/windowsforms-drag-drop-toolbox.jpeg)
changed

2023-06-23 08:44 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172143-Windowsforms-links](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/608/console)**

2023-06-23 08:45 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172143-Windowsforms-links](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/608/)<br/>**

2023-06-23 09:19 UTC, MallikaRK approved these changes
Approved

2023-06-26 09:59 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-06-26 09:59 UTC, merged