SEO-172150-WindowsForms-Changes-Web
syncfusion-content/windowsforms-docs pull request #569
Opened 2023-05-29 08:57 UTC by Sharly-Atieno

Hi @Aishwarya-Ganesan,
Renamed image alt text. Kindly review.

Regards,
Sharly A.

2023-06-01 08:09 UTC, MallikaRK approved these changes
Approved

2023-06-05 13:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172150-WindowsForms-Changes-Web](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/587/console)**

2023-06-05 13:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172150-WindowsForms-Changes-Web](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/587/)<br/>**

2023-06-05 14:17 UTC, MallikaRK requested changes
Commented

2023-06-05 14:17 UTC, MallikaRK commented on WindowsForms/TextBox/Getting-Started.md
> +![Drag and drop TextBoxExt from toolbox in WindowsForms application](Creating-TextBoxExt_images/windowsforms-textbox-drag-and-drop.png)
Image Folder name in Upper case. It also produce redirect to small case.
So, you should change the image folder name to small casing. Check and correct in all places.

2023-06-05 14:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172150-WindowsForms-Changes-Web](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/588/console)**

2023-06-09 11:47 UTC, Girija-Rajendran approved these changes

2023-06-09 11:48 UTC, merged