SEO-172143-Windowsforms-links-changes
syncfusion-content/windowsforms-docs pull request #570
Opened 2023-05-29 09:44 UTC by Scholar-jaruha

Hi @MallikaRK ,
Please review the changes made.
Regards,
Scholar.

2023-05-29 09:45 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172143-Windowsforms-links-changes](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/555/console)**

2023-05-29 09:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172143-Windowsforms-links-changes](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/555/)<br/>**

2023-06-12 09:30 UTC, MallikaRK requested changes
Commented

2023-06-12 09:30 UTC, MallikaRK commented on WindowsForms/Grouping/Getting-Started.md
> +   ![WindowsForms Grouping Creating a Windows Application](getting-started_images/windowsforms-create-windows-application.jpeg)
Control name is missing in image name.
<img width="588" alt="image" src="https://github.com/syncfusion-content/windowsforms-docs/assets/44014283/78d8838d-1e0e-49c3-85b6-d2b2957f3511">
 check and update the control name in all places.

2023-06-12 09:30 UTC, MallikaRK commented on WindowsForms/Html-Viewer/Getting-Started.md
> +![HTMLUIControl added using code](getting-started_images/windowsforms-adding-code.png)
Image name don't have the control name. Check and update the control name in all places.

2023-06-14 08:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172143-Windowsforms-links-changes](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/598/console)**

2023-06-14 08:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172143-Windowsforms-links-changes](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/598/)<br/>**

2023-06-21 05:46 UTC, MallikaRK requested changes
Commented

2023-06-21 05:46 UTC, MallikaRK commented on WindowsForms/Html-Viewer/Getting-Started.md
> +![Drag an drop the HTML UI  control in WindowsForms application](getting-started_images/windowsforms-html-viewer-drag-drop-html.png)
Image name has repeated html keyword.
Change like as below,
adding-html-viewer-control-through-designer

2023-06-21 05:46 UTC, MallikaRK commented on WindowsForms/groupview/Overview.md
> +![Overview of Group View in WindowsForms](overview_images/windowsforms-group-viewoverview.png)
recheck the image name. give hyphen properly.

2023-06-23 08:48 UTC, Scholar-jaruha commented on WindowsForms/Html-Viewer/Getting-Started.md
> +![Drag an drop the HTML UI  control in WindowsForms application](getting-started_images/windowsforms-html-viewer-drag-drop-html.png)
changed

2023-06-23 08:57 UTC, Scholar-jaruha commented on WindowsForms/groupview/Overview.md
> +![Overview of Group View in WindowsForms](overview_images/windowsforms-group-viewoverview.png)
Added hyphen in the image name

2023-06-23 09:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172143-Windowsforms-links-changes](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/609/)<br/>**

2023-06-23 09:21 UTC, MallikaRK approved these changes
Approved

2023-06-26 10:08 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-06-26 10:08 UTC, merged