SEO-172173 Windows Forms Changes
syncfusion-content/windowsforms-docs pull request #577
Opened 2023-05-30 09:48 UTC by Scholar-jaruha

Hi @MallikaRK ,
please review the changes made.
Regards,
Scholar.

2023-05-30 09:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171173-Windows-Forms-Changes](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/562/)<br/>**

2023-05-30 11:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171173-Windows-Forms-Changes](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/565/console)**

2023-05-30 11:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171173-Windows-Forms-Changes](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/565/)<br/>**

2023-06-12 09:37 UTC, MallikaRK requested changes
Commented

2023-06-12 09:37 UTC, MallikaRK commented on WindowsForms/ListView/GettingStarted.md
> +![Drag and drop the SfListView control into WindowsForms application](getting-started_images/windowsforms-drag-drop.png)
WF also fine. Don't change.
Control name missing in image name.
Check and add the control name in all places.

2023-06-14 09:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171173-Windows-Forms-Changes](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/600/console)**

2023-06-14 10:01 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171173-Windows-Forms-Changes](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/600/)<br/>**

2023-06-21 05:52 UTC, MallikaRK approved these changes
Approved

2023-06-22 10:30 UTC, Girija-Rajendran commented on WindowsForms/MaskedTextBox/Overview.md
> +![Overview of Syncfusion MaskedEditBox](MaskedEditBox-images/windowsforms-masked-edit-box-overview.png)
<img width="375" alt="image" src="https://github.com/syncfusion-content/windowsforms-docs/assets/61148953/c5004d49-aa2f-434d-96b3-6e54ac201e77">

2023-06-23 08:18 UTC, Scholar-jaruha commented on WindowsForms/MaskedTextBox/Overview.md
> +![Overview of Syncfusion MaskedEditBox](MaskedEditBox-images/windowsforms-masked-edit-box-overview.png)
changed

2023-06-23 08:18 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171173-Windows-Forms-Changes](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/606/console)**

2023-06-23 08:19 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171173-Windows-Forms-Changes](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/606/)<br/>**

2023-06-26 10:11 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-06-26 10:11 UTC, merged