SEO-174775 WindowsForms Page with redirect
syncfusion-content/windowsforms-docs pull request #629
Opened 2023-08-02 09:46 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan,

Have worked on changing WindowsForms Page with Redirect UG, please review.

Regards,
Yvone.

2023-08-02 09:48 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-174775-WIndowsForms-Page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/622/console)**

2023-08-02 09:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174775-WIndowsForms-Page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/622/console)**

2023-08-02 09:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-174775-WIndowsForms-Page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/622/)<br/>**

2023-08-08 05:34 UTC, MallikaRK requested changes
Commented

2023-08-08 05:34 UTC, MallikaRK commented on WindowsForms/Grid-Control/Undo-Redo.md
> +GridControl gives support for Undo/Redo functionality. GridControl keeps a track on all the operations undergone, in a particular class [GridModelCommandManager](https://help.syncfusion.com/cr/window
https://help.syncfusion.com/cr/windowsforms/Syncfusion.Windows.Forms.Grid.GridModelCommandManager.html

why you maintain # symbol is needed?

2023-08-08 05:34 UTC, MallikaRK commented on WindowsForms/Grid-Control/Undo-Redo.md
> +GridControl gives support for Undo/Redo functionality. GridControl keeps a track on all the operations undergone, in a particular class [GridModelCommandManager](https://help.syncfusion.com/cr/window
Recheck all the links and update it.

2023-08-08 06:31 UTC, Yvone-Atieno commented on WindowsForms/Grid-Control/Undo-Redo.md
> +GridControl gives support for Undo/Redo functionality. GridControl keeps a track on all the operations undergone, in a particular class [GridModelCommandManager](https://help.syncfusion.com/cr/window
updated

2023-08-08 06:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174775-WIndowsForms-Page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/625/console)**

2023-08-08 06:34 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-174775-WIndowsForms-Page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/625/)<br/>**

2023-08-08 10:11 UTC, MallikaRK approved these changes
Approved

2023-08-08 11:10 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-08-08 11:11 UTC, merged