UG Content for PdfToImageConverter
syncfusion-content/windowsforms-docs pull request #653
Opened 2023-08-25 05:25 UTC by KrithikaGanesan

UG Content for PdfToImageConverter

2023-08-25 05:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [pdftoimage](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/634/console)**

2023-08-25 05:27 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [pdftoimage](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/634/)<br/>**

2023-08-25 06:53 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [pdftoimage](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/635/console)**

2023-08-25 06:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [pdftoimage](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/635/console)**

2023-08-25 06:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [pdftoimage](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/635/)<br/>**

2023-09-05 07:19 UTC, Vikassekar requested changes

2023-09-05 07:19 UTC, Vikassekar commented on WindowsForms/PDF-Viewer/Getting-Started.md
> +N> Starting with v23.1.x, Syncfusion.PdfToImageConverter.Base assembly is required for PdfViewer.
"Starting with version 23.1.x, a reference to the Syncfusion.PdfToImageConverter.Base assembly is necessary for PdfViewer applications."
Can you change content as above?

2023-09-05 07:38 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [pdftoimage](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/636/console)**

2023-09-05 07:38 UTC, KrithikaGanesan commented on WindowsForms/PDF-Viewer/Getting-Started.md
> +N> Starting with v23.1.x, Syncfusion.PdfToImageConverter.Base assembly is required for PdfViewer.
Yes. I have changed the content as above

2023-09-05 07:39 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [pdftoimage](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/636/)<br/>**

2023-09-13 11:27 UTC, Vikassekar approved these changes

2023-09-13 11:27 UTC, merged