SEO-175680-Windowsforms-UG-page-with-redirects-link
syncfusion-content/windowsforms-docs pull request #666
Opened 2023-09-13 14:56 UTC by Edithabich

Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.

Regards,
Edith.

2023-09-13 14:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-Windowsforms-UG-page-with-redirects-link](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/644/console)**

2023-09-13 14:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-Windowsforms-UG-page-with-redirects-link](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/644/)<br/>**

2023-09-21 12:32 UTC, Yvone-Atieno requested changes
Commented

2023-09-21 12:32 UTC, Yvone-Atieno commented on WindowsForms/GridGrouping/Grid-Layout.md
> +In GridGroupingControl, if freeze columns exceed client area then the horizontal scroll bar will become invisible. To overcome this some of the customizations has to be done. You have to make use of
Update correct cr links

2023-09-22 09:16 UTC, Edithabich commented on WindowsForms/GridGrouping/Grid-Layout.md
> +In GridGroupingControl, if freeze columns exceed client area then the horizontal scroll bar will become invisible. To overcome this some of the customizations has to be done. You have to make use of
Resolved comments

2023-09-22 09:16 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-175680-Windowsforms-UG-page-with-redirects-link](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/652/console)**

2023-09-22 09:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-Windowsforms-UG-page-with-redirects-link](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/652/console)**

2023-09-22 09:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-Windowsforms-UG-page-with-redirects-link](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/652/)<br/>**

2023-09-27 11:21 UTC, Yvone-Atieno requested changes
Commented

2023-09-27 11:21 UTC, Yvone-Atieno commented on WindowsForms/GridGrouping/Filtering.md
> +The [RecordFilters](https://help.syncfusion.com/cr/windowsforms/Syncfusion.Grouping.RecordFilterDescriptorCollection.html) otherwise known as `RowFilters` will allow users to restrict displayed recor
Update this link - https://help.syncfusion.com/cr/windowsforms/Syncfusion.Grouping.TableDescriptor.html#Syncfusion_Grouping_TableDescriptor_RecordFilters

2023-09-28 06:39 UTC, Edithabich commented on WindowsForms/GridGrouping/Filtering.md
> +The [RecordFilters](https://help.syncfusion.com/cr/windowsforms/Syncfusion.Grouping.RecordFilterDescriptorCollection.html) otherwise known as `RowFilters` will allow users to restrict displayed recor
udated

2023-09-28 06:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-Windowsforms-UG-page-with-redirects-link](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/664/console)**

2023-09-28 06:51 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-Windowsforms-UG-page-with-redirects-link](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/664/)<br/>**

2023-09-28 07:43 UTC, Yvone-Atieno approved these changes
Approved

2023-10-05 08:11 UTC, Yvone-Atieno approved these changes
Approved

2023-10-18 14:26 UTC, Aishwarya-Ganesan approved these changes
Fine.

2023-10-18 14:26 UTC, merged