SEO-176062-Windowsforms-UG-duplicate-title
syncfusion-content/windowsforms-docs pull request #686
Opened 2023-09-27 11:17 UTC by Edithabich

HI @MallikaRK ,
Have updated UG titles please review.
Thanks.

Regards,
Edith Abich.

2023-09-27 11:18 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Windowsforms-UG-duplicate-title](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/654/console)**

2023-09-27 11:19 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windowsforms-UG-duplicate-title](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/654/)<br/>**

2023-10-06 08:49 UTC, Yvone-Atieno requested changes
Commented

2023-10-06 08:49 UTC, Yvone-Atieno commented on WindowsForms/GridRecordNavigationControl/Overview.md
> +title: Overview of Windows Forms GridRecordNavigationControl | Syncfusion
Overview of Windows Forms Grid Record Navigation Control | Syncfusion

2023-10-06 08:49 UTC, Yvone-Atieno commented on WindowsForms/Numeric-TextBox/Overview.md
> +title: Overview of Windows Forms Numeric TextBox control | Syncfusion
Control the first word should be in caps, check in all places

2023-10-06 08:49 UTC, Yvone-Atieno commented on WindowsForms/Scroll-Frame/OverView.md
> +title: Overview of Windows Forms Scroll Frame control | Syncfusion
Control the first word should be in caps.

2023-10-10 13:21 UTC, Edithabich commented on WindowsForms/Scroll-Frame/OverView.md
> +title: Overview of Windows Forms Scroll Frame control | Syncfusion
Resolved

2023-10-10 13:21 UTC, Edithabich commented on WindowsForms/Numeric-TextBox/Overview.md
> +title: Overview of Windows Forms Numeric TextBox control | Syncfusion
Resolved

2023-10-10 13:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Windowsforms-UG-duplicate-title](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/701/console)**

2023-10-10 13:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windowsforms-UG-duplicate-title](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/701/)<br/>**

2023-10-10 13:38 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Windowsforms-UG-duplicate-title](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/703/console)**

2023-10-10 13:39 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windowsforms-UG-duplicate-title](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/703/)<br/>**

2023-10-12 12:49 UTC, Yvone-Atieno approved these changes
Approved

2023-11-01 11:34 UTC, closed without merging