SEO-176062 -Windowsforms-UG -Duplicate title
syncfusion-content/windowsforms-docs pull request #688
Opened 2023-09-27 12:24 UTC by Edithabich

HI @MallikaRK ,
Have updated UG titles please review.
Thanks.

Regards,
Edith Abich.

2023-09-27 12:25 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Windowsforms-duplicate-title](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/656/console)**

2023-09-27 12:29 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windowsforms-duplicate-title](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/656/)<br/>**

2023-10-06 09:02 UTC, Yvone-Atieno requested changes
Commented

2023-10-06 09:02 UTC, Yvone-Atieno commented on WindowsForms/skins/Overview.md
> +title: Overview of Windows Forms skins control | Syncfusion
Overview of Windows Forms Skins Control | Syncfusion

2023-10-10 13:58 UTC, Edithabich commented on WindowsForms/MultiColumn-ComboBox/Overview.md
> +title: Overview of Windows Forms MultiColumnComboBox control | Syncfusion
resolved

2023-10-10 13:58 UTC, Edithabich commented on WindowsForms/layoutmanagers/GridLayout/Overview.md
> +title: Overview of Windows Forms LayoutManagers control | Syncfusion
resolved

2023-10-10 13:59 UTC, Edithabich commented on WindowsForms/skins/Overview.md
> +title: Overview of Windows Forms skins control | Syncfusion
resolved

2023-10-12 12:53 UTC, Yvone-Atieno approved these changes
Approved

2023-11-01 11:37 UTC, closed without merging