SEO-176062-Windowsforms-duplicate-Ug-titles
syncfusion-content/windowsforms-docs pull request #690
Opened 2023-09-27 12:55 UTC by Edithabich

HI @MallikaRK ,
Have updated UG titles please review.
Thanks.

Regards,
Edith Abich.

2023-09-27 12:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windowsforms-duplicate-Ug-titles](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/658/)<br/>**

2023-10-06 09:12 UTC, Yvone-Atieno requested changes
Commented

2023-10-06 09:12 UTC, Yvone-Atieno commented on WindowsForms/Classic/ComboBox/Overview.md
> +title: Overview of Windows Forms ComboBoxAdv control | Syncfusion
Overview of Windows Forms ComboBox Control | Syncfusion

2023-10-06 09:12 UTC, Yvone-Atieno commented on WindowsForms/Classic/Currency-Edit/Overview.md
> +title: Overview of Windows Forms CurrencyEdit control | Syncfusion
Control, the first letter should be in caps

2023-10-10 14:19 UTC, Edithabich commented on WindowsForms/Classic/Currency-Edit/Overview.md
> +title: Overview of Windows Forms CurrencyEdit control | Syncfusion
resolved

2023-10-10 14:19 UTC, Edithabich commented on WindowsForms/Classic/ComboBox/Overview.md
> +title: Overview of Windows Forms ComboBoxAdv control | Syncfusion
resolved

2023-10-10 14:20 UTC, Edithabich commented on WindowsForms/Classic/Currency-Edit/Overview.md
> +title: Overview of Windows Forms CurrencyEdit control | Syncfusion
resolved

2023-10-10 14:21 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Windowsforms-duplicate-Ug-titles](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/706/console)**

2023-10-12 13:03 UTC, Yvone-Atieno requested changes
Commented

2023-10-12 13:03 UTC, Yvone-Atieno commented on WindowsForms/layoutmanagers/CardLayout/Overview.md
> +title: Overview of Windows Forms CardLayout Control | Syncfusion
Use LayoutManagers

2023-10-17 11:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Windowsforms-duplicate-Ug-titles](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/728/console)**

2023-10-17 11:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windowsforms-duplicate-Ug-titles](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/728/)<br/>**

2023-11-01 11:38 UTC, closed without merging