SEO-176062-Windowsforms-duplicate-titles
syncfusion-content/windowsforms-docs pull request #691
Opened 2023-09-27 13:17 UTC by Edithabich

HI @MallikaRK ,
Have updated UG titles please review.
Thanks.

Regards,
Edith Abich.

2023-10-06 09:15 UTC, Yvone-Atieno requested changes
Commented

2023-10-06 09:15 UTC, Yvone-Atieno commented on WindowsForms/Classic/DateTimePicker/Overview.md
> +title: Overview of Windows Forms DateTimePicker control | Syncfusion
Control

2023-10-06 09:15 UTC, Yvone-Atieno commented on WindowsForms/MessageBox/Overview.md
> +title: Overview of Windows Forms MessageBoxAdv control | Syncfusion
Overview of Windows Forms MessageBox Control | Syncfusion

2023-10-10 14:34 UTC, Edithabich commented on WindowsForms/MessageBox/Overview.md
> +title: Overview of Windows Forms MessageBoxAdv control | Syncfusion
resolved

2023-10-10 14:50 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-176062-Windowsforms-duplicate-titles](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/708/console)**

2023-10-10 14:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Windowsforms-duplicate-titles](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/708/console)**

2023-10-10 14:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windowsforms-duplicate-titles](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/708/)<br/>**

2023-11-01 11:38 UTC, closed without merging