SEO-176062-Windows-forms-duplicate-title
syncfusion-content/windowsforms-docs pull request #692
Opened 2023-09-27 13:50 UTC by Edithabich

HI @MallikaRK ,
Have updated UG titles please review.
Thanks.

Regards,
Edith Abich.

2023-09-27 13:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-title](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/660/)<br/>**

2023-10-06 09:55 UTC, Yvone-Atieno requested changes
Commented

2023-10-06 09:55 UTC, Yvone-Atieno commented on WindowsForms/Classic/Month-Calendar/Overview.md
> +title: Overview of Windows Forms Month Calendar control | Syncfusion
Overview of Windows Forms CalendarDateTime Control | Syncfusion

2023-10-06 09:55 UTC, Yvone-Atieno commented on WindowsForms/Calculation-Engine/Overview.md
> +title: Overview of Windows Forms Calculation Engine control | Syncfusion
C under Control should be in caps. Check in all places.

2023-10-10 14:47 UTC, Edithabich commented on WindowsForms/Classic/Month-Calendar/Overview.md
> +title: Overview of Windows Forms Month Calendar control | Syncfusion
resolved

2023-10-10 14:47 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-title](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/707/console)**

2023-10-10 14:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-title](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/707/)<br/>**

2023-10-12 13:13 UTC, Yvone-Atieno requested changes
Commented

2023-10-12 13:13 UTC, Yvone-Atieno commented on WindowsForms/ComboBox-DropDown/Overview.md
> +title: Overview of Windows Forms ComboBox DropDown Control | Syncfusion
Use ComboDropDown

2023-10-12 13:13 UTC, Yvone-Atieno commented on WindowsForms/Overview.md
> +title: Overview of Windows Forms | Syncfusion
Overview of Essential Studio Windows Forms products | Syncfusion

2023-10-17 11:47 UTC, Edithabich commented on WindowsForms/ComboBox-DropDown/Overview.md
> +title: Overview of Windows Forms ComboBox DropDown Control | Syncfusion
resolved

2023-10-17 11:47 UTC, Edithabich commented on WindowsForms/Overview.md
> +title: Overview of Windows Forms | Syncfusion
resolved

2023-10-17 11:47 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-title](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/729/console)**

2023-10-17 11:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-title](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/729/)<br/>**

2023-11-01 11:38 UTC, closed without merging