SEO- 176062 windows forms duplicate titles
syncfusion-content/windowsforms-docs pull request #693
Opened 2023-09-27 14:16 UTC by Edithabich

HI @MallikaRK ,
Have updated UG titles please review.
Thanks.

Regards,
Edith Abich.

2023-09-27 14:30 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-titles](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/661/)<br/>**

2023-10-06 09:52 UTC, Yvone-Atieno requested changes
Commented

2023-10-06 09:52 UTC, Yvone-Atieno commented on WindowsForms/ComboBox/Overview.md
> +title: Overview of Windows Forms ComboBox control | Syncfusion
Control, C should be in caps. Check in all places

2023-10-10 15:07 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-titles](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/709/console)**

2023-10-10 15:08 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-titles](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/709/console)**

2023-10-10 15:16 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-titles](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/709/)<br/>**

2023-10-12 13:15 UTC, Yvone-Atieno requested changes
Commented

2023-10-12 13:15 UTC, Yvone-Atieno commented on WindowsForms/Form/Overview.md
> +title: Overview of Windows Forms Control | Syncfusion
Overview of Windows Forms Form Control | Syncfusion

2023-10-12 13:15 UTC, Yvone-Atieno commented on WindowsForms/layoutmanagers/BorderLayout/Overview.md
> +title: Overview of Windows Forms BorderLayout Control | Syncfusion
Overview of Windows Forms LayoutManagers Control | Syncfusion

2023-10-17 11:54 UTC, Edithabich commented on WindowsForms/Form/Overview.md
> +title: Overview of Windows Forms Control | Syncfusion
resolved

2023-10-17 11:54 UTC, Edithabich commented on WindowsForms/layoutmanagers/BorderLayout/Overview.md
> +title: Overview of Windows Forms BorderLayout Control | Syncfusion
resolved

2023-10-17 11:54 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-titles](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/730/console)**

2023-10-17 12:08 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-titles](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/730/console)**

2023-10-17 12:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-titles](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/730/)<br/>**

2023-11-01 11:39 UTC, closed without merging