SEO-176062 windows forms duplicate title
syncfusion-content/windowsforms-docs pull request #694
Opened 2023-09-27 14:29 UTC by Edithabich

Hi @MallikaRK ,
Have updated UG titles please review.
Thanks.

Regards,
Edith Abich.

2023-09-27 14:30 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-title-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/662/console)**

2023-09-27 14:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-title-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/662/)<br/>**

2023-10-06 09:51 UTC, Yvone-Atieno requested changes
Commented

2023-10-06 09:51 UTC, Yvone-Atieno commented on WindowsForms/Barcode/Overview.md
> +title: Overview of Windows Forms Barcode control | Syncfusion
Should start with caps. Check in all places
<img width="338" alt="image" src="https://github.com/syncfusion-content/windowsforms-docs/assets/95272306/e8d1afaa-7079-4951-97f0-f5f3ce2f4d94">

2023-10-10 15:17 UTC, Edithabich commented on WindowsForms/Barcode/Overview.md
> +title: Overview of Windows Forms Barcode control | Syncfusion
resolved

2023-10-10 15:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-title-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/710/)<br/>**

2023-11-01 11:39 UTC, closed without merging