SEO-176062-Windows-forms-duplicate-titles-
syncfusion-content/windowsforms-docs pull request #695
Opened 2023-09-27 14:42 UTC by Edithabich

Hi @MallikaRK ,
Have updated UG titles please review.
Thanks.

Regards,
Edith Abich.

2023-09-27 14:43 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-titles-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/663/console)**

2023-10-06 09:48 UTC, Yvone-Atieno requested changes
Commented

2023-10-06 09:48 UTC, Yvone-Atieno commented on WindowsForms/DICOM/Overview.md
> +title: Overview of Windows Forms Dicom control | Syncfusion
The first word should be in caps under Control. Check in all places.

2023-10-10 15:39 UTC, Edithabich commented on WindowsForms/DICOM/Overview.md
> +title: Overview of Windows Forms Dicom control | Syncfusion
resolved

2023-10-10 15:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-titles-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/711/console)**

2023-10-10 15:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-titles-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/711/)<br/>**

2023-10-12 13:20 UTC, Yvone-Atieno requested changes
Commented

2023-10-12 13:20 UTC, Yvone-Atieno commented on WindowsForms/TabControl/Overview.md
> +title: Overview of Windows Forms TabControl | Syncfusion
Overview of Windows Forms TabControl Control | Syncfusion

2023-10-17 11:59 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-titles-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/731/console)**

2023-10-17 12:01 UTC, Edithabich commented on WindowsForms/TabControl/Overview.md
> +title: Overview of Windows Forms TabControl | Syncfusion
resolved

2023-10-17 12:10 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Windows-forms-duplicate-titles-](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/731/)<br/>**

2023-11-01 11:40 UTC, closed without merging