SEO-176113-Pages-With-Redirects-WinForms1
syncfusion-content/windowsforms-docs pull request #720
Opened 2023-10-09 09:18 UTC by berylouma

Hello,

I have worked on links with redirects.

Kind regards,
Beryl

2023-10-09 09:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176113-Pages-With-Redirects-WinForms1](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/697/console)**

2023-10-09 09:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176113-Pages-With-Redirects-WinForms1](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/697/)<br/>**

2023-10-11 13:29 UTC, Yvone-Atieno requested changes
Commented

2023-10-11 13:29 UTC, Yvone-Atieno commented on WindowsForms/GridGrouping/Navigation-Bar.md
> +The style of the `NavigationBar` can be changed by using the [GridOfficeScrollBar](https://help.syncfusion.com/cr/windowsforms/Syncfusion.Windows.Forms.Grid.Grouping.GridGroupingControl.html#Syncfusi
Update scrolling link
<img width="491" alt="image" src="https://github.com/syncfusion-content/windowsforms-docs/assets/95272306/b7a70b9a-c0f6-44b5-b907-9c662a13b04f">

2023-10-11 13:29 UTC, Yvone-Atieno commented on WindowsForms/GridGrouping/Grouping.md
>  * [GroupCollapsed](https://help.syncfusion.com/cr/windowsforms/Syncfusion.Windows.Forms.Grid.Grouping.GridGroupingControl.html) - Occurs after a group is collapsed.
Update the below link - https://help.syncfusion.com/cr/windowsforms/Syncfusion.Windows.Forms.Grid.Grouping.GridGroupingControl.html#Syncfusion_Windows_Forms_Grid_Grouping_GridGroupingControl_GroupCollapsed

2023-10-11 13:29 UTC, Yvone-Atieno commented on WindowsForms/GridGrouping/Grouping.md
>  * [GroupCollapsing](https://help.syncfusion.com/cr/windowsforms/Syncfusion.Windows.Forms.Grid.Grouping.GridGroupingControl.html) - Occurs before a group is collapsed.
Update the correct link

2023-10-17 08:46 UTC, berylouma commented on WindowsForms/GridGrouping/Exporting.md
>  It caches the `SparklineGroup` that needs to be added to the Excel sheet. The spark lines will be appear once the user select the data range and the location range. Data range and reference range for
Updated

2023-10-17 08:47 UTC, berylouma commented on WindowsForms/GridGrouping/Navigation-Bar.md
> +The style of the `NavigationBar` can be changed by using the [GridOfficeScrollBar](https://help.syncfusion.com/cr/windowsforms/Syncfusion.Windows.Forms.Grid.Grouping.GridGroupingControl.html#Syncfusi
Updated

2023-10-17 08:53 UTC, berylouma commented on WindowsForms/GridGrouping/Grouping.md
>  * [GroupCollapsed](https://help.syncfusion.com/cr/windowsforms/Syncfusion.Windows.Forms.Grid.Grouping.GridGroupingControl.html) - Occurs after a group is collapsed.
Updated

2023-10-17 08:55 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176113-Pages-With-Redirects-WinForms1](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/721/console)**

2023-10-17 08:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176113-Pages-With-Redirects-WinForms1](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/721/)<br/>**

2023-11-14 11:42 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-176113-Pages-With-Redirects-WinForms1](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/747/console)**

2023-11-14 11:44 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176113-Pages-With-Redirects-WinForms1](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/747/console)**

2023-11-14 11:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176113-Pages-With-Redirects-WinForms1](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/747/)<br/>**

2023-11-22 06:34 UTC, Yvone-Atieno approved these changes
Approved

2023-12-07 11:22 UTC, Aishwarya-Ganesan approved these changes
> fine.

2023-12-07 11:22 UTC, merged