SEO-177279-Page-With-Redirect-WF
syncfusion-content/windowsforms-docs pull request #764
Opened 2023-11-14 07:33 UTC by berylouma

Hello,

I have worked on links with redirects.

Regards,
Beryl.

2023-11-14 07:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-177279-Page-With-Redirect-WF](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/745/console)**

2023-11-14 07:35 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-177279-Page-With-Redirect-WF](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/745/)<br/>**

2023-11-17 07:49 UTC, Yvone-Atieno requested changes
Commented

2023-11-17 07:49 UTC, Yvone-Atieno commented on WindowsForms/DataGrid/Merging.md
> +The [QueryCoveredRangeEventArgs](https://help.syncfusion.com/cr/windowsforms/Syncfusion.WinForms.DataGrid.SfDataGrid.html#Syncfusion_WinForms_DataGrid_SfDataGrid_QueryCoveredRange) of the QueryCovere
Update this link under QueryCoveredRangeEventArgs
https://help.syncfusion.com/cr/windowsforms/Syncfusion.WinForms.DataGrid.Events.QueryCoveredRangeEventArgs.html

2023-11-22 11:47 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-177279-Page-With-Redirect-WF](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/756/console)**

2023-11-22 11:49 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-177279-Page-With-Redirect-WF](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/756/console)**

2023-11-22 11:52 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-177279-Page-With-Redirect-WF](https://jenkins.syncfusion.com/job/Content/job/windowsforms-docs/756/)<br/>**

2023-11-23 06:36 UTC, Yvone-Atieno approved these changes
Approved

2023-12-07 11:26 UTC, Aishwarya-Ganesan approved these changes
fine.

2023-12-07 11:26 UTC, merged