SEO-179238 WindowsForms Page with Redirect
syncfusion-content/windowsforms-docs pull request #839
Opened 2024-01-26 11:50 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan ,
Have changed Page with Redirect links.
Regards,
Yvone.

2024-01-26 11:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-179238-WindowsForms-Page-with-Redirect](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/20/console)**

2024-01-26 11:53 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-179238-WindowsForms-Page-with-Redirect](https://ci.syncfusion.com/job/Content/job/WindowsForms-docs/20/)<br/>**

2024-01-29 13:11 UTC, MallikaRK requested changes
Commented

2024-01-29 13:11 UTC, MallikaRK commented on WindowsForms/Installation/web-installer/how-to-download.md
> +4. After downloading, the Syncfusion Windows Forms web installer can be unlocked using either the trial unlock key or the Syncfusion registered login credential. More information on generating an unl
remove the additional url parameter
![Uploading image.png…]()

2024-01-29 13:11 UTC, MallikaRK commented on WindowsForms/Installation/web-installer/how-to-download.md
> +4. After you've started the trial, go to the [Trials & Downloads](https://www.syncfusion.com/account/manage-trials/downloads) page to get the latest version trial installer. You can generate the [unl
remove here too.

2024-01-29 13:16 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-179238-WindowsForms-Page-with-Redirect](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/22/console)**

2024-01-29 13:16 UTC, Yvone-Atieno commented on WindowsForms/Installation/web-installer/how-to-download.md
> +4. After downloading, the Syncfusion Windows Forms web installer can be unlocked using either the trial unlock key or the Syncfusion registered login credential. More information on generating an unl
removed

2024-01-29 13:16 UTC, Yvone-Atieno commented on WindowsForms/Installation/web-installer/how-to-download.md
> +4. After you've started the trial, go to the [Trials & Downloads](https://www.syncfusion.com/account/manage-trials/downloads) page to get the latest version trial installer. You can generate the [unl
removed

2024-01-29 13:21 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-179238-WindowsForms-Page-with-Redirect](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/22/console)**

2024-01-29 13:22 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-179238-WindowsForms-Page-with-Redirect](https://ci.syncfusion.com/job/Content/job/WindowsForms-docs/22/)<br/>**

2024-01-30 04:34 UTC, MallikaRK approved these changes
approved

2024-01-30 13:21 UTC, merged