SEO-180844-WinForms-refering-page
syncfusion-content/windowsforms-docs pull request #932
Opened 2024-04-12 08:34 UTC by Edithabich

Hi @gowthamanthavasiyappan,
Kindly review the referring links issue fixes changes.

Thanks.

Regards,
Edith.

2024-04-12 08:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-180844-WinForms-refering-page](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/57/console)**

2024-04-12 08:41 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/57/artifact/cireports/)<br/>Build Location: [SEO-180844-WinForms-refering-page](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/57/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/57/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/57/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/57/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/57/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/57/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/57/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/57/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/57/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-04-12 08:59 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-180844-WinForms-refering-page](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/59/console)**

2024-04-12 13:02 UTC, gowthamanthavasiyappan requested changes
Commented

2024-04-12 13:02 UTC, gowthamanthavasiyappan commented on WindowsForms/Status-Bar/StatusBarAdv-Overview.md
> +![WindowsForm Status Bar overview.](Overview_images/windowsform-status-bar-overview.jpeg)
Windowsforms - change like this [both places]
![image](https://github.com/syncfusion-content/windowsforms-docs/assets/90315799/fa21c97d-4ff9-4be1-894f-e6fd39928fa7)

2024-04-12 13:22 UTC, Edithabich commented on WindowsForms/Status-Bar/StatusBarAdv-Overview.md
> +![WindowsForm Status Bar overview.](Overview_images/windowsform-status-bar-overview.jpeg)
resolved

2024-04-12 13:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-180844-WinForms-refering-page](https://ci.syncfusion.com/job/Content/job/windowsforms-docs/64/console)**

2024-04-15 04:38 UTC, gowthamanthavasiyappan approved these changes
Approved

2024-04-23 13:24 UTC, merged